### ISSUE TITLE
Confusing description of redis sentinel in documentation

### ISSUE THREAD

**Issue by akamitch** [pberkel/caddy-storage-redis#14]
I use Caddy with plugin caddy-storage-redis.
With single redis instance all works fine.
Now i’d like to use redis sentinel.
Looks like plugin is ready for it, according to sample for redis sentinel.
But, i was confused that u used redis port 6379 in example.

        address {
            redis-sentinal-001.example.com:6379
            redis-sentinal-002.example.com:6379
            redis-sentinal-003.example.com:6379
        }
According to documentation, application should use redis sentinel nodes, receive from them current redis master and use it.
But, how do the Caddy will know if master fail, and sentinel promote new master?
I don’t see how Caddy connects to sentinel in this sample configuration.

May be it is mistake in the config sample, and port should be 26379 ?
Or Caddy may directly ask redis nodes about replication status and remember who is the master?

**Comment by pberkel** [comment]
Hi @akamitch thanks for your question, my understanding is that when configuring the Redis client to connect to Sentinel for failover, you provide the address of one or more Sentinel servers (not the Redis server) and specify the Redis master server name:

```
{
    storage redis failover {
        address {
            redis-sentinal-001.example.com:26379
            redis-sentinal-002.example.com:26379
            redis-sentinal-003.example.com:26379
        }
        master_name redis-master-server
    }
}
```

I have updated the module documentation to help clarify.
